[2022-06-16 10:17:09,020] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: analytics.getdata manual__2022-06-16T10:16:45.194238+00:00 [queued]>
[2022-06-16 10:17:09,175] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: analytics.getdata manual__2022-06-16T10:16:45.194238+00:00 [queued]>
[2022-06-16 10:17:09,227] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-16 10:17:09,243] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-16 10:17:09,280] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-16 10:17:09,870] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): getdata> on 2022-06-16 10:16:45.194238+00:00
[2022-06-16 10:17:10,111] {standard_task_runner.py:52} INFO - Started process 2491 to run task
[2022-06-16 10:17:10,182] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'analytics', 'getdata', 'manual__2022-06-16T10:16:45.194238+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/testing_etl.py', '--cfg-path', '/tmp/tmpx01fb13v', '--error-file', '/tmp/tmpxncd0617']
[2022-06-16 10:17:10,221] {standard_task_runner.py:80} INFO - Job 115: Subtask getdata
[2022-06-16 10:17:11,817] {task_command.py:370} INFO - Running <TaskInstance: analytics.getdata manual__2022-06-16T10:16:45.194238+00:00 [running]> on host fe209149cfc1
[2022-06-16 10:17:15,794] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=analytics
AIRFLOW_CTX_TASK_ID=getdata
AIRFLOW_CTX_EXECUTION_DATE=2022-06-16T10:16:45.194238+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-16T10:16:45.194238+00:00
[2022-06-16 10:17:15,796] {mysql.py:82} INFO - Executing: SELECT * from Customer_T;
[2022-06-16 10:17:15,867] {base.py:68} INFO - Using connection ID 'mysql_con' for task execution.
[2022-06-16 10:17:16,026] {dbapi.py:213} INFO - Running statement: SELECT * from Customer_T;, parameters: None
[2022-06-16 10:17:16,030] {dbapi.py:221} INFO - Rows affected: 19
[2022-06-16 10:17:16,156] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=analytics, task_id=getdata, execution_date=20220616T101645, start_date=20220616T101709, end_date=20220616T101716
[2022-06-16 10:17:16,454] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-16 10:17:16,763] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
